'use strict'

let questions = [
    {
        "question": "frage 1?",
        "answer_1": "Antwort 1",
        "answer_2": "Antwort 2",
        "answer_3": "Antwort 3",
        "answer_4": "Antwort 4",
        "correctAnswerNumber": 4,
    },
    {
        "question": "frage 2?",
        "answer_1": "Antwort 1",
        "answer_2": "Antwort 2",
        "answer_3": "Antwort 3",
        "answer_4": "Antwort 4",
        "correctAnswerNumber": 2,
    },
    {
        "question": "frage 3?",
        "answer_1": "Antwort 1",
        "answer_2": "Antwort 2",
        "answer_3": "Antwort 3",
        "answer_4": "Antwort 4",
        "correctAnswerNumber": 2,
    },
    {
        "question": "frage 4?",
        "answer_1": "Antwort 1",
        "answer_2": "Antwort 2",
        "answer_3": "Antwort 3",
        "answer_4": "Antwort 4",
        "correctAnswerNumber": 3,
    },
    {
        "question": "frage 5?",
        "answer_1": "Antwort 1",
        "answer_2": "Antwort 2",
        "answer_3": "Antwort 3",
        "answer_4": "Antwort 4",
        "correctAnswerNumber": 1,
    },
    {
        "question": "frage 6?",
        "answer_1": "Antwort 1",
        "answer_2": "Antwort 2",
        "answer_3": "Antwort 3",
        "answer_4": "Antwort 4",
        "correctAnswerNumber": 3,
    },
    {
        "question": "frage 7?",
        "answer_1": "Antwort 1",
        "answer_2": "Antwort 2",
        "answer_3": "Antwort 3",
        "answer_4": "Antwort 4",
        "correctAnswerNumber": 1,
    },
    {
        "question": "frage 8?",
        "answer_1": "Antwort 1",
        "answer_2": "Antwort 2",
        "answer_3": "Antwort 3",
        "answer_4": "Antwort 4",
        "correctAnswerNumber": 2,
    },
    {
        "question": "frage 9?",
        "answer_1": "Antwort 1",
        "answer_2": "Antwort 2",
        "answer_3": "Antwort 3",
        "answer_4": "Antwort 4",
        "correctAnswerNumber": 1,
    },
    {
        "question": "frage 10?",
        "answer_1": "Antwort 1",
        "answer_2": "Antwort 2",
        "answer_3": "Antwort 3",
        "answer_4": "Antwort 4",
        "correctAnswerNumber": 4,
    },
    {
        "question": "frage 11?",
        "answer_1": "Antwort 1",
        "answer_2": "Antwort 2",
        "answer_3": "Antwort 3",
        "answer_4": "Antwort 4",
        "correctAnswerNumber": 4,
    },
    {
        "question": "frage 12?",
        "answer_1": "Antwort 1",
        "answer_2": "Antwort 2",
        "answer_3": "Antwort 3",
        "answer_4": "Antwort 4",
        "correctAnswerNumber": 2,
    },

];