'use strict'

let questions = [
    {
        "question": "Wann wurde das Kolosseum erbaut?",
        "answer_1": "100 n. Chr.",
        "answer_2": "320 n. Chr.",
        "answer_3": "20 v. Chr.",
        "answer_4": "72 n. Chr.",
        "correctAnswerNumber": 4,
    },
    {
        "question": "Wer verlor 1978 das Finale der Fußball-WM gegen den Gastgeber Argentinen?",
        "answer_1": "Deutschland",
        "answer_2": "Niederlande",
        "answer_3": "Italien",
        "answer_4": "Frankreich",
        "correctAnswerNumber": 2,
    },
    {
        "question": "Wer spielte im Film 'Das Boot' von 1981 mit?",
        "answer_1": "Udo Lindenberg",
        "answer_2": "Herbert Grönemeyer",
        "answer_3": "Roland Emmerich",
        "answer_4": "Klaus Kinski",
        "correctAnswerNumber": 2,
    },
    {
        "question": "Wie hoch ist der Eiffelturm in Paris?",
        "answer_1": "179 Meter",
        "answer_2": "278 Meter",
        "answer_3": "324 Meter",
        "answer_4": "58 Meter",
        "correctAnswerNumber": 3,
    },
    {
        "question": "Wieviel Megabyte ergeben 1 Gigabyte?",
        "answer_1": "1000 Megabyte",
        "answer_2": "2048 Megabyte",
        "answer_3": "500 Megabyte",
        "answer_4": "1012 Megabyte",
        "correctAnswerNumber": 1,
    },
    {
        "question": "Was für ein Tier ist Flip aus Biene Maja?",
        "answer_1": "Regenwurm",
        "answer_2": "Biene",
        "answer_3": "Grashüpfer",
        "answer_4": "Marienkäfer",
        "correctAnswerNumber": 3,
    },
    {
        "question": "Wie ist das englische Wort für 'Löffel'?",
        "answer_1": "spoon",
        "answer_2": "spane",
        "answer_3": "spine",
        "answer_4": "spleen",
        "correctAnswerNumber": 1,
    },
    {
        "question": "In welchem Jahr entdeckte Christoph Kolumbus Amerika?",
        "answer_1": "1490",
        "answer_2": "1492",
        "answer_3": "1491",
        "answer_4": "1493",
        "correctAnswerNumber": 2,
    },
    {
        "question": "Welches Land ist kein Nachbarland von Frankreich?",
        "answer_1": "Niederlande",
        "answer_2": "Italien",
        "answer_3": "Schweiz",
        "answer_4": "Luxemburg",
        "correctAnswerNumber": 1,
    },
    {
        "question": "Wieviele Inseln gehören zu Griechenland?",
        "answer_1": "5763",
        "answer_2": "125",
        "answer_3": "2005",
        "answer_4": "3054",
        "correctAnswerNumber": 4,
    },
    {
        "question": "Was ist keine griechische Insel?",
        "answer_1": "Kos",
        "answer_2": "Kreta",
        "answer_3": "Rhodos",
        "answer_4": "Laos",
        "correctAnswerNumber": 4,
    },
    {
        "question": "Wer spielte 'Han Solo' in Star Wars?",
        "answer_1": "Sam Neill",
        "answer_2": "Harrison Ford",
        "answer_3": "Mark Hamill",
        "answer_4": "Liam Neeson",
        "correctAnswerNumber": 2,
    },
    {
        "question": "Wer gehört nicht zu den 'drei Fragezeichen'?",
        "answer_1": "Justus Jonas",
        "answer_2": "Tim Burton",
        "answer_3": "Bob Andrews",
        "answer_4": "Peter Shaw",
        "correctAnswerNumber": 2,
    },
    {
        "question": "Wie alt wurde Queen Elizabeth II.?",
        "answer_1": "91 Jahre",
        "answer_2": "96 Jahre",
        "answer_3": "98 Jahre",
        "answer_4": "99 Jahre",
        "correctAnswerNumber": 2,
    },
    {
        "question": "Wie heißt das Wahrzeichen von Kleve am Niederrhein?",
        "answer_1": "Burg Eltz",
        "answer_2": "Schwanenburg",
        "answer_3": "Schloß Neuschwanstein",
        "answer_4": "Elisabethkirche",
        "correctAnswerNumber": 2,
    },
    {
        "question": "Wie heißt die Hauptstadt von Estland?",
        "answer_1": "Vilnius",
        "answer_2": "Tallin",
        "answer_3": "Oslo",
        "answer_4": "Minsk",
        "correctAnswerNumber": 2,
    },
    {
        "question": "Welche Währung hat Südafrika?",
        "answer_1": "Rind",
        "answer_2": "Rand",
        "answer_3": "Rund",
        "answer_4": "Runt",
        "correctAnswerNumber": 2,
    },
    {
        "question": "Wer heißt die Hauptstand von Italien?",
        "answer_1": "Madrid",
        "answer_2": "Rom",
        "answer_3": "Neapel",
        "answer_4": "Verona",
        "correctAnswerNumber": 2,
    },
    {
        "question": "In welchem Jahr wurde Deutschland NICHT Fußball-Weltmeister?",
        "answer_1": "1954",
        "answer_2": "1994",
        "answer_3": "2014",
        "answer_4": "1974",
        "correctAnswerNumber": 2,
    },
    {
        "question": "Wer schrieb 'Alice im Wunderland'?",
        "answer_1": "Jim Carroll",
        "answer_2": "Lewis Carroll",
        "answer_3": "John Carroll",
        "answer_4": "Richard Carroll",
        "correctAnswerNumber": 2,
    },
    {
        "question": "Aus welchem Jahr stammt der Film 'Jurassic Park'?",
        "answer_1": "1989",
        "answer_2": "1993",
        "answer_3": "1997",
        "answer_4": "2003",
        "correctAnswerNumber": 2,
    },
    {
        "question": "Wer sang 'Über den Wolken'?",
        "answer_1": "Peter Maffay",
        "answer_2": "Reinhard Mey",
        "answer_3": "Udo Jürgens",
        "answer_4": "Herbert Grönemeyer",
        "correctAnswerNumber": 2,
    },
    {
        "question": "Wer schrieb 'Der Herr der Ringe'?",
        "answer_1": "J.K. Rowling",
        "answer_2": "J.R.R. Tolkien",
        "answer_3": "H.G. Wells",
        "answer_4": "J.D. Salinger",
        "correctAnswerNumber": 2,
    },
    {
        "question": "Wie hoch ist das Brandenburger Tor?",
        "answer_1": "41 Meter",
        "answer_2": "26 Meter",
        "answer_3": "35 Meter",
        "answer_4": "30 Meter",
        "correctAnswerNumber": 2,
    },
   
];